[mypy]
python_version = 3.11
warn_unused_configs = True
ignore_missing_imports = True
disable_error_code = import-untyped
show_error_codes = True
show_column_numbers = True
pretty = False
color_output = False
incremental = False
